-- VIEW

/*
    <VIEW>
        SELECT 문을 저장할 수 있는 객체이다.(논리적인 가상 테이블)
        데이터를 저장하고 있지 않으며 테이블에 대한 SQL만 저장되어 있어 VIEW 접근할 때 SQL을 수행하면서 결과값을 가져온다.
        
        [문법]
            CREATE [OR REPLACE] VIEW 뷰명
            AS 서브 쿼리;
*/

-- 한국에서 근무하는 사원들의 사번,이름,부서명,급여, 근무 국가명 조회
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, SALARY, NATIONAL_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
JOIN NATIONAL N ON L.NATIONAL_CODE = N.NATIONAL_CODE
WHERE N.NATIONAL_NAME = '한국';

-- 일본에서 근무하는 사원들의 사번,이름,부서명,급여, 근무 국가명 조회
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, SALARY, NATIONAL_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
JOIN NATIONAL N ON L.NATIONAL_CODE = N.NATIONAL_CODE
WHERE N.NATIONAL_NAME = '일본';

-- VIEW
CREATE OR REPLACE VIEW V_EMPLOYEE
AS
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, SALARY, NATIONAL_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.DEPT_ID
JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
JOIN NATIONAL N ON L.NATIONAL_CODE = N.NATIONAL_CODE
;


SELECT * FROM V_EMPLOYEE;

-- 한국에서 근무하는 사원들의 사번,이름,부서명,급여, 근무 국가명 조회
SELECT * 
FROM V_EMPLOYEE
WHERE NATIONAL_NAME = '한국';


-- DML
COMMIT;
UPDATE V_EMPLOYEE
SET SALARY = 999999999
WHERE EMP_NAME = '선동일'
;

SELECT * FROM V_EMPLOYEE;
SELECT * FROM EMPLOYEE;
ROLLBACK;


-- READ ONLY
CREATE OR REPLACE VIEW V_DEPT_01
AS
SELECT *
FROM DEPARTMENT
WITH READ ONLY
;

SELECT * FROM USER_VIEWS;
SELECT VIEW_NAME, READ_ONLY FROM USER_VIEWS;



























