-- DDL (CREATE)

/*
    DDL
        데이터 정의 언어
        객체 생성, 변경, 삭제 등
        실제 데이터 값이 아닌, 데이터의 구조 자체를 정의하는 언어
        
        * 오라클 객체 : 테이블, 뷰, 시퀀스, 인덱스, 트리거, 프로시져, 함수, 사용자 등...
*/

--DROP TABLE TB_MEMBER;
CREATE TABLE TB_MEMBER(
    ID VARCHAR2(30)
    , PWD VARCHAR2(100)
    , NAME VARCHAR2(20)
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
);

DESC TB_MEMBER;
SELECT * FROM TB_MEMBER;

COMMENT ON COLUMN TB_MEMBER.ID IS '회원아이디';

/*
    제약조건 (CONSTRAINT)
        사용자가 원하는 조건의 데이터만 유지하기 위해서 사용
        데이터 무결성 보장을 목적으로 함 (정확성, 일관성 유지)
        
        * NOT NULL, UNIQUE, CHECK, PRIMARY KEY, FOREIGN KEY
*/

-- 제약 조건 확인
DESC USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONSTRAINTS WHERE OWNER = 'C##KH';

-- 제약조건이 걸린 칼럼 조회
DESC USER_CONS_COLUMNS;
SELECT * FROM USER_CONS_COLUMNS;

-- NOT NULL : 해당 칼럼에 반드시 값이 있어야 하는 경우
INSERT INTO TB_MEMBER VALUES(NULL, NULL, NULL, NULL);
SELECT * FROM TB_MEMBER;

-- 테이블 생성
--DROP TABLE TB_MEMBER;
CREATE TABLE TB_MEMBER(
    ID VARCHAR2(30) NOT NULL
    , PWD VARCHAR2(100) NOT NULL
    , NAME VARCHAR2(20) NOT NULL
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
);

-- 테이블 생성
--DROP TABLE TB_MEMBER;
CREATE TABLE TB_MEMBER(
    ID VARCHAR2(30) NOT NULL UNIQUE
    , PWD VARCHAR2(100) NOT NULL UNIQUE
    , NAME VARCHAR2(20) NOT NULL UNIQUE
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
);

INSERT INTO TB_MEMBER (ID, PWD, NAME) VALUES('USER01', '1234' , 'SWY');
SELECT * FROM TB_MEMBER;


-- 테이블 생성
DROP TABLE TB_MEMBER;
CREATE TABLE TB_MEMBER(
    ID VARCHAR2(30) CONSTRAINT MEMBER_ID_NN NOT NULL
    , PWD VARCHAR2(100) 
    , NAME VARCHAR2(20) CONSTRAINT MEMBER_NAME_UQ UNIQUE
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
);

INSERT INTO TB_MEMBER (ID, PWD, NAME) VALUES('ZZZ', '1234' , 'SWY');
SELECT * FROM TB_MEMBER;


-- 테이블 생성
DROP TABLE TB_MEMBER;
CREATE TABLE TB_MEMBER(
    ID VARCHAR2(30) CONSTRAINT MEMBER_ID_NN NOT NULL
    , PWD VARCHAR2(100) 
    , NAME VARCHAR2(20)
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
    , CONSTRAINT MEMBER_ID_PWD_NAME_UQ UNIQUE(ID , PWD, NAME)
);

INSERT INTO TB_MEMBER (ID, PWD, NAME) VALUES('ZZZ', '4321' , 'SWY');
SELECT * FROM TB_MEMBER;

INSERT INTO TB_MEMBER (ID, PWD, NAME, ENROLL_DATE) VALUES('USER01', '1234' , 'NAME01', DEFAULT);
SELECT * FROM TB_MEMBER;

DROP TABLE TB_MEMBER;


-- CHECK 제약조건
DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    NO NUMBER CONSTRAINT NNNNN CHECK(NO > 0)
    , NICK VARCHAR2(100) NOT NULL
    , NAME VARCHAR2(100) 
    , GENDER CHAR(1) CONSTRAINT ZZZ CHECK(GENDER IN ('M' , 'F'))
    , CONSTRAINT ABC CHECK (NAME != NICK)
);

INSERT INTO STUDENT VALUES(1, '심원용', '심원용', 'M');
INSERT INTO STUDENT VALUES(1, '심원용', 'X');
SELECT * FROM STUDENT;


-- 기본키

































