-- MEMBER 테이블
DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
    MEMBER_ID       VARCHAR2(50)
    , MEMBER_PWD    VARCHAR2(100)
    , MEMBER_NICK   VARCHAR2(50)
    , ENROLL_DATE   TIMESTAMP DEFAULT SYSDATE
);

-- 이하 내용은 삭제할 것
